### ISSUE TITLE
Failed to load DocumentLiteralWrappedRequestHeaderMessageBinder

### ISSUE THREAD

**Issue by deguif** [BeSimple/BeSimpleSoap#45]
This class doesn't exist.

But it is requested in **Resources/config/webservice.xml** by the key _besimple.soap.binder.request_header.documentwrapped.class_

So when using _document/literal/wrapped_, the class **WebServiceContext** emit a fatal error by emitting a **ClassNotFoundException**

**Comment by benrcole** [comment]
Hi, Is document-wrapped going to be an option at all?
