### ISSUE TITLE
Documentation site is down?

### ISSUE THREAD

**Issue by bizmate** [BeSimple/BeSimpleSoap#72]
Maybe it will get fixed while i post the issue. However i cannot access the documentation at bisim.pl and it looks like it is not just me. 

http://downforeveryoneorjustme.com/bisim.pl

Is the documentation being moved?

**Comment by bizmate** [comment]
It's not just you! http://bisim.pl looks down from here.
Check another site?

Is downtime destroying your website & business? 
Time for a dependable web host - Special Offer!

Short URL at isup.me

**Comment by francisbesset** [comment]
Hello,
The URL is http://besim.pl :

```
It's just you. http://besim.pl is up.
```

**Comment by filipzelic** [comment]
Hello,

Documentation site is down again for some time now.

**Comment by ghost** [comment]
Please your help. I need to build a soao request. with besimplesoapbundle

thanks
