### ISSUE TITLE
Mime parser drops lines that start with a hyphen.

### ISSUE THREAD

**Issue by ubermichael** [BeSimple/BeSimpleSoap#87]
The Mime parser drops lines that start with a single hyphen. It considers them as the start of a boundary, and when they don't match it moves on to the next line. It should append the line to the content.

Patch and test coming.

**Comment by guilhermeadc** [comment]
This fix needs to be applied as soon as possible. This problem is corrupting various files, mostly PDFs, received by the SOAP + MTOM.

**Comment by wollanup** [comment]
@guilhermeadc +1
I had same issue mostly with PDF files and spent a lot of time to figure it out.
Applying proposed solve the issue, at least for one corrupted file, which is now correct.

Any news about merging the related PR ?
